trigger:
- master

pool:
  vmImage: 'Ubuntu-16.04'

steps:

- script: |
    sudo apt update
    sudo apt install -y autoconf
    sudo apt install -y automake
    sudo apt install -y libtool
    sudo apt install -y swig
    git clone https://github.com/wiredtiger/wiredtiger
    cd wiredtiger/
    git checkout -qf 81305b4ade4b92bde247931334c99c32fb148c44
    sh autogen.sh
    ./configure -enable-java
    make
    sudo make install
    sudo cp /usr/local/lib/libwiredtiger* /usr/local/share/java/wiredtiger-3.1.0/
    cd ../
    sudo mkdir /etc/fennec
    sudo chown -R $(id -u):$(id -g) /etc/fennec
  displayName: 'Install WiredTiger'

- script: |
    ./gradlew assemble
    ./gradlew check --info
  displayName: 'Run fennec'
