// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resc/proto/Fennec.proto

package db.fennec.proto;

public interface FDataProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:db.fennec.proto.FDataProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>double value = 1;</code>
   */
  double getValue();

  /**
   * <code>int64 timestamp = 2;</code>
   */
  long getTimestamp();
}
