// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resc/proto/Fennec.proto

package db.fennec.proto;

/**
 * Protobuf type {@code db.fennec.proto.FNamespacesProto}
 */
public  final class FNamespacesProto extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:db.fennec.proto.FNamespacesProto)
    FNamespacesProtoOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FNamespacesProto.newBuilder() to construct.
  private FNamespacesProto(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FNamespacesProto() {
    ns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FNamespacesProto(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            java.lang.String s = input.readStringRequireUtf8();
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              ns_ = new com.google.protobuf.LazyStringArrayList();
              mutable_bitField0_ |= 0x00000001;
            }
            ns_.add(s);
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        ns_ = ns_.getUnmodifiableView();
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return db.fennec.proto.FennecProto.internal_static_db_fennec_proto_FNamespacesProto_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return db.fennec.proto.FennecProto.internal_static_db_fennec_proto_FNamespacesProto_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            db.fennec.proto.FNamespacesProto.class, db.fennec.proto.FNamespacesProto.Builder.class);
  }

  public static final int NS_FIELD_NUMBER = 1;
  private com.google.protobuf.LazyStringList ns_;
  /**
   * <code>repeated string ns = 1;</code>
   */
  public com.google.protobuf.ProtocolStringList
      getNsList() {
    return ns_;
  }
  /**
   * <code>repeated string ns = 1;</code>
   */
  public int getNsCount() {
    return ns_.size();
  }
  /**
   * <code>repeated string ns = 1;</code>
   */
  public java.lang.String getNs(int index) {
    return ns_.get(index);
  }
  /**
   * <code>repeated string ns = 1;</code>
   */
  public com.google.protobuf.ByteString
      getNsBytes(int index) {
    return ns_.getByteString(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < ns_.size(); i++) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 1, ns_.getRaw(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    {
      int dataSize = 0;
      for (int i = 0; i < ns_.size(); i++) {
        dataSize += computeStringSizeNoTag(ns_.getRaw(i));
      }
      size += dataSize;
      size += 1 * getNsList().size();
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof db.fennec.proto.FNamespacesProto)) {
      return super.equals(obj);
    }
    db.fennec.proto.FNamespacesProto other = (db.fennec.proto.FNamespacesProto) obj;

    boolean result = true;
    result = result && getNsList()
        .equals(other.getNsList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getNsCount() > 0) {
      hash = (37 * hash) + NS_FIELD_NUMBER;
      hash = (53 * hash) + getNsList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static db.fennec.proto.FNamespacesProto parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static db.fennec.proto.FNamespacesProto parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static db.fennec.proto.FNamespacesProto parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static db.fennec.proto.FNamespacesProto parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static db.fennec.proto.FNamespacesProto parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static db.fennec.proto.FNamespacesProto parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static db.fennec.proto.FNamespacesProto parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static db.fennec.proto.FNamespacesProto parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static db.fennec.proto.FNamespacesProto parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static db.fennec.proto.FNamespacesProto parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static db.fennec.proto.FNamespacesProto parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static db.fennec.proto.FNamespacesProto parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(db.fennec.proto.FNamespacesProto prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code db.fennec.proto.FNamespacesProto}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:db.fennec.proto.FNamespacesProto)
      db.fennec.proto.FNamespacesProtoOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return db.fennec.proto.FennecProto.internal_static_db_fennec_proto_FNamespacesProto_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return db.fennec.proto.FennecProto.internal_static_db_fennec_proto_FNamespacesProto_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              db.fennec.proto.FNamespacesProto.class, db.fennec.proto.FNamespacesProto.Builder.class);
    }

    // Construct using db.fennec.proto.FNamespacesProto.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      ns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return db.fennec.proto.FennecProto.internal_static_db_fennec_proto_FNamespacesProto_descriptor;
    }

    public db.fennec.proto.FNamespacesProto getDefaultInstanceForType() {
      return db.fennec.proto.FNamespacesProto.getDefaultInstance();
    }

    public db.fennec.proto.FNamespacesProto build() {
      db.fennec.proto.FNamespacesProto result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public db.fennec.proto.FNamespacesProto buildPartial() {
      db.fennec.proto.FNamespacesProto result = new db.fennec.proto.FNamespacesProto(this);
      int from_bitField0_ = bitField0_;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        ns_ = ns_.getUnmodifiableView();
        bitField0_ = (bitField0_ & ~0x00000001);
      }
      result.ns_ = ns_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof db.fennec.proto.FNamespacesProto) {
        return mergeFrom((db.fennec.proto.FNamespacesProto)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(db.fennec.proto.FNamespacesProto other) {
      if (other == db.fennec.proto.FNamespacesProto.getDefaultInstance()) return this;
      if (!other.ns_.isEmpty()) {
        if (ns_.isEmpty()) {
          ns_ = other.ns_;
          bitField0_ = (bitField0_ & ~0x00000001);
        } else {
          ensureNsIsMutable();
          ns_.addAll(other.ns_);
        }
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      db.fennec.proto.FNamespacesProto parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (db.fennec.proto.FNamespacesProto) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private com.google.protobuf.LazyStringList ns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
    private void ensureNsIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        ns_ = new com.google.protobuf.LazyStringArrayList(ns_);
        bitField0_ |= 0x00000001;
       }
    }
    /**
     * <code>repeated string ns = 1;</code>
     */
    public com.google.protobuf.ProtocolStringList
        getNsList() {
      return ns_.getUnmodifiableView();
    }
    /**
     * <code>repeated string ns = 1;</code>
     */
    public int getNsCount() {
      return ns_.size();
    }
    /**
     * <code>repeated string ns = 1;</code>
     */
    public java.lang.String getNs(int index) {
      return ns_.get(index);
    }
    /**
     * <code>repeated string ns = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNsBytes(int index) {
      return ns_.getByteString(index);
    }
    /**
     * <code>repeated string ns = 1;</code>
     */
    public Builder setNs(
        int index, java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureNsIsMutable();
      ns_.set(index, value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string ns = 1;</code>
     */
    public Builder addNs(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  ensureNsIsMutable();
      ns_.add(value);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string ns = 1;</code>
     */
    public Builder addAllNs(
        java.lang.Iterable<java.lang.String> values) {
      ensureNsIsMutable();
      com.google.protobuf.AbstractMessageLite.Builder.addAll(
          values, ns_);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string ns = 1;</code>
     */
    public Builder clearNs() {
      ns_ = com.google.protobuf.LazyStringArrayList.EMPTY;
      bitField0_ = (bitField0_ & ~0x00000001);
      onChanged();
      return this;
    }
    /**
     * <code>repeated string ns = 1;</code>
     */
    public Builder addNsBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      ensureNsIsMutable();
      ns_.add(value);
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:db.fennec.proto.FNamespacesProto)
  }

  // @@protoc_insertion_point(class_scope:db.fennec.proto.FNamespacesProto)
  private static final db.fennec.proto.FNamespacesProto DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new db.fennec.proto.FNamespacesProto();
  }

  public static db.fennec.proto.FNamespacesProto getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FNamespacesProto>
      PARSER = new com.google.protobuf.AbstractParser<FNamespacesProto>() {
    public FNamespacesProto parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FNamespacesProto(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FNamespacesProto> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FNamespacesProto> getParserForType() {
    return PARSER;
  }

  public db.fennec.proto.FNamespacesProto getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

