// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resc/proto/Fennec.proto

package db.fennec.proto;

public interface FNamespacesProtoOrBuilder extends
    // @@protoc_insertion_point(interface_extends:db.fennec.proto.FNamespacesProto)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string ns = 1;</code>
   */
  java.util.List<java.lang.String>
      getNsList();
  /**
   * <code>repeated string ns = 1;</code>
   */
  int getNsCount();
  /**
   * <code>repeated string ns = 1;</code>
   */
  java.lang.String getNs(int index);
  /**
   * <code>repeated string ns = 1;</code>
   */
  com.google.protobuf.ByteString
      getNsBytes(int index);
}
