// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resc/proto/PantheraService.proto

package db.fennec.proto;

public interface PantheraListTablesRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:db.fennec.proto.PantheraListTablesRequest)
    com.google.protobuf.MessageOrBuilder {
}
