// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resc/proto/PantheraService.proto

package db.fennec.proto;

public interface PantheraListTablesResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:db.fennec.proto.PantheraListTablesResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int32 statusCode = 1;</code>
   */
  int getStatusCode();

  /**
   * <code>string statusMsg = 2;</code>
   */
  java.lang.String getStatusMsg();
  /**
   * <code>string statusMsg = 2;</code>
   */
  com.google.protobuf.ByteString
      getStatusMsgBytes();

  /**
   * <code>repeated string table = 3;</code>
   */
  java.util.List<java.lang.String>
      getTableList();
  /**
   * <code>repeated string table = 3;</code>
   */
  int getTableCount();
  /**
   * <code>repeated string table = 3;</code>
   */
  java.lang.String getTable(int index);
  /**
   * <code>repeated string table = 3;</code>
   */
  com.google.protobuf.ByteString
      getTableBytes(int index);
}
