// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resc/proto/PantheraService.proto

package db.fennec.proto;

public interface PantheraGetMultiResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:db.fennec.proto.PantheraGetMultiResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated .db.fennec.proto.PantheraGetResponse responses = 1;</code>
   */
  java.util.List<db.fennec.proto.PantheraGetResponse> 
      getResponsesList();
  /**
   * <code>repeated .db.fennec.proto.PantheraGetResponse responses = 1;</code>
   */
  db.fennec.proto.PantheraGetResponse getResponses(int index);
  /**
   * <code>repeated .db.fennec.proto.PantheraGetResponse responses = 1;</code>
   */
  int getResponsesCount();
  /**
   * <code>repeated .db.fennec.proto.PantheraGetResponse responses = 1;</code>
   */
  java.util.List<? extends db.fennec.proto.PantheraGetResponseOrBuilder> 
      getResponsesOrBuilderList();
  /**
   * <code>repeated .db.fennec.proto.PantheraGetResponse responses = 1;</code>
   */
  db.fennec.proto.PantheraGetResponseOrBuilder getResponsesOrBuilder(
      int index);
}
