// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resc/proto/PantheraService.proto

package db.fennec.proto;

public interface PantheraGetKeySliceRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:db.fennec.proto.PantheraGetKeySliceRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string table = 1;</code>
   */
  java.lang.String getTable();
  /**
   * <code>string table = 1;</code>
   */
  com.google.protobuf.ByteString
      getTableBytes();

  /**
   * <code>int64 start = 2;</code>
   */
  long getStart();

  /**
   * <code>int32 size = 3;</code>
   */
  int getSize();
}
