// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resc/proto/PantheraService.proto

package db.fennec.proto;

public interface PantheraGetKeysResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:db.fennec.proto.PantheraGetKeysResponse)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>repeated string key = 1;</code>
   */
  java.util.List<java.lang.String>
      getKeyList();
  /**
   * <code>repeated string key = 1;</code>
   */
  int getKeyCount();
  /**
   * <code>repeated string key = 1;</code>
   */
  java.lang.String getKey(int index);
  /**
   * <code>repeated string key = 1;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes(int index);
}
