// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: resc/proto/PantheraService.proto

package db.fennec.proto;

public interface PantheraGetRequestOrBuilder extends
    // @@protoc_insertion_point(interface_extends:db.fennec.proto.PantheraGetRequest)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string table = 1;</code>
   */
  java.lang.String getTable();
  /**
   * <code>string table = 1;</code>
   */
  com.google.protobuf.ByteString
      getTableBytes();

  /**
   * <code>string key = 2;</code>
   */
  java.lang.String getKey();
  /**
   * <code>string key = 2;</code>
   */
  com.google.protobuf.ByteString
      getKeyBytes();
}
