/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package db.fennec.dashboard

import kotlin.test.Test
import kotlin.test.assertNotNull

class AppTest {
    @Test
    fun testAppHasAGreeting() {
        val classUnderTest = MainComponent()
        assertNotNull(classUnderTest.greeting, "app should have a greeting")
    }
}
