// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FennecService.proto

package db.fennec.api.proto;

public final class FennecServiceProto {
  private FennecServiceProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_db_fennec_api_proto_FStatus_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_db_fennec_api_proto_FStatus_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_db_fennec_api_proto_FQueryReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_db_fennec_api_proto_FQueryReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_db_fennec_api_proto_FQueryResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_db_fennec_api_proto_FQueryResp_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_db_fennec_api_proto_FWriteReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_db_fennec_api_proto_FWriteReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_db_fennec_api_proto_FRemoveReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_db_fennec_api_proto_FRemoveReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_db_fennec_api_proto_FRemoveNSReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_db_fennec_api_proto_FRemoveNSReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_db_fennec_api_proto_FListReq_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_db_fennec_api_proto_FListReq_fieldAccessorTable;
  static final com.google.protobuf.Descriptors.Descriptor
    internal_static_db_fennec_api_proto_FListResp_descriptor;
  static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_db_fennec_api_proto_FListResp_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023FennecService.proto\022\023db.fennec.api.pro" +
      "to\032\014Fennec.proto\"/\n\007FStatus\022\023\n\013status_co" +
      "de\030\001 \001(\003\022\017\n\007message\030\002 \001(\t\"Z\n\tFQueryReq\022\r" +
      "\n\005field\030\001 \001(\t\022\021\n\tnamespace\030\002 \001(\t\022\024\n\014in_r" +
      "ange_low\030\003 \001(\003\022\025\n\rin_range_high\030\004 \001(\003\"i\n" +
      "\nFQueryResp\022,\n\006status\030\001 \001(\0132\034.db.fennec." +
      "api.proto.FStatus\022-\n\006result\030\002 \001(\0132\035.db.f" +
      "ennec.proto.FResultProto\">\n\tFWriteReq\0221\n" +
      "\007payload\030\001 \003(\0132 .db.fennec.proto.FDataEn" +
      "tryProto\"[\n\nFRemoveReq\022\024\n\014in_range_low\030\001" +
      " \001(\003\022\025\n\rin_range_high\030\002 \001(\003\022\r\n\005field\030\003 \001" +
      "(\t\022\021\n\tnamespace\030\004 \001(\t\"!\n\014FRemoveNSReq\022\021\n" +
      "\tnamespace\030\001 \001(\t\",\n\010FListReq\022\r\n\005field\030\001 " +
      "\001(\t\022\021\n\tnamespace\030\002 \001(\t\"H\n\tFListResp\022,\n\006s" +
      "tatus\030\001 \001(\0132\034.db.fennec.api.proto.FStatu" +
      "s\022\r\n\005field\030\002 \003(\t2\306\003\n\rFennecService\022H\n\005qu" +
      "ery\022\036.db.fennec.api.proto.FQueryReq\032\037.db" +
      ".fennec.api.proto.FQueryResp\022F\n\006insert\022\036" +
      ".db.fennec.api.proto.FWriteReq\032\034.db.fenn" +
      "ec.api.proto.FStatus\022F\n\006upsert\022\036.db.fenn" +
      "ec.api.proto.FWriteReq\032\034.db.fennec.api.p" +
      "roto.FStatus\022G\n\006remove\022\037.db.fennec.api.p" +
      "roto.FRemoveReq\032\034.db.fennec.api.proto.FS" +
      "tatus\022K\n\010removeNS\022!.db.fennec.api.proto." +
      "FRemoveNSReq\032\034.db.fennec.api.proto.FStat" +
      "us\022E\n\004list\022\035.db.fennec.api.proto.FListRe" +
      "q\032\036.db.fennec.api.proto.FListRespB\026B\022Fen" +
      "necServiceProtoP\001b\006proto3"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          db.fennec.proto.FennecProto.getDescriptor(),
        }, assigner);
    internal_static_db_fennec_api_proto_FStatus_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_db_fennec_api_proto_FStatus_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_db_fennec_api_proto_FStatus_descriptor,
        new java.lang.String[] { "StatusCode", "Message", });
    internal_static_db_fennec_api_proto_FQueryReq_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_db_fennec_api_proto_FQueryReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_db_fennec_api_proto_FQueryReq_descriptor,
        new java.lang.String[] { "Field", "Namespace", "InRangeLow", "InRangeHigh", });
    internal_static_db_fennec_api_proto_FQueryResp_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_db_fennec_api_proto_FQueryResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_db_fennec_api_proto_FQueryResp_descriptor,
        new java.lang.String[] { "Status", "Result", });
    internal_static_db_fennec_api_proto_FWriteReq_descriptor =
      getDescriptor().getMessageTypes().get(3);
    internal_static_db_fennec_api_proto_FWriteReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_db_fennec_api_proto_FWriteReq_descriptor,
        new java.lang.String[] { "Payload", });
    internal_static_db_fennec_api_proto_FRemoveReq_descriptor =
      getDescriptor().getMessageTypes().get(4);
    internal_static_db_fennec_api_proto_FRemoveReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_db_fennec_api_proto_FRemoveReq_descriptor,
        new java.lang.String[] { "InRangeLow", "InRangeHigh", "Field", "Namespace", });
    internal_static_db_fennec_api_proto_FRemoveNSReq_descriptor =
      getDescriptor().getMessageTypes().get(5);
    internal_static_db_fennec_api_proto_FRemoveNSReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_db_fennec_api_proto_FRemoveNSReq_descriptor,
        new java.lang.String[] { "Namespace", });
    internal_static_db_fennec_api_proto_FListReq_descriptor =
      getDescriptor().getMessageTypes().get(6);
    internal_static_db_fennec_api_proto_FListReq_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_db_fennec_api_proto_FListReq_descriptor,
        new java.lang.String[] { "Field", "Namespace", });
    internal_static_db_fennec_api_proto_FListResp_descriptor =
      getDescriptor().getMessageTypes().get(7);
    internal_static_db_fennec_api_proto_FListResp_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_db_fennec_api_proto_FListResp_descriptor,
        new java.lang.String[] { "Status", "Field", });
    db.fennec.proto.FennecProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
