// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FennecService.proto

package db.fennec.api.proto;

public interface FListRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:db.fennec.api.proto.FListResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.db.fennec.api.proto.FStatus status = 1;</code>
   */
  boolean hasStatus();
  /**
   * <code>.db.fennec.api.proto.FStatus status = 1;</code>
   */
  db.fennec.api.proto.FStatus getStatus();
  /**
   * <code>.db.fennec.api.proto.FStatus status = 1;</code>
   */
  db.fennec.api.proto.FStatusOrBuilder getStatusOrBuilder();

  /**
   * <code>repeated string field = 2;</code>
   */
  java.util.List<java.lang.String>
      getFieldList();
  /**
   * <code>repeated string field = 2;</code>
   */
  int getFieldCount();
  /**
   * <code>repeated string field = 2;</code>
   */
  java.lang.String getField(int index);
  /**
   * <code>repeated string field = 2;</code>
   */
  com.google.protobuf.ByteString
      getFieldBytes(int index);
}
