// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FennecService.proto

package db.fennec.api.proto;

public interface FListReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:db.fennec.api.proto.FListReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string field = 1;</code>
   */
  java.lang.String getField();
  /**
   * <code>string field = 1;</code>
   */
  com.google.protobuf.ByteString
      getFieldBytes();

  /**
   * <code>string namespace = 2;</code>
   */
  java.lang.String getNamespace();
  /**
   * <code>string namespace = 2;</code>
   */
  com.google.protobuf.ByteString
      getNamespaceBytes();
}
