// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FennecService.proto

package db.fennec.api.proto;

/**
 * Protobuf type {@code db.fennec.api.proto.FQueryResp}
 */
public  final class FQueryResp extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:db.fennec.api.proto.FQueryResp)
    FQueryRespOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FQueryResp.newBuilder() to construct.
  private FQueryResp(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FQueryResp() {
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FQueryResp(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            db.fennec.api.proto.FStatus.Builder subBuilder = null;
            if (status_ != null) {
              subBuilder = status_.toBuilder();
            }
            status_ = input.readMessage(db.fennec.api.proto.FStatus.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(status_);
              status_ = subBuilder.buildPartial();
            }

            break;
          }
          case 18: {
            db.fennec.proto.FResultProto.Builder subBuilder = null;
            if (result_ != null) {
              subBuilder = result_.toBuilder();
            }
            result_ = input.readMessage(db.fennec.proto.FResultProto.parser(), extensionRegistry);
            if (subBuilder != null) {
              subBuilder.mergeFrom(result_);
              result_ = subBuilder.buildPartial();
            }

            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return db.fennec.api.proto.FennecServiceProto.internal_static_db_fennec_api_proto_FQueryResp_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return db.fennec.api.proto.FennecServiceProto.internal_static_db_fennec_api_proto_FQueryResp_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            db.fennec.api.proto.FQueryResp.class, db.fennec.api.proto.FQueryResp.Builder.class);
  }

  public static final int STATUS_FIELD_NUMBER = 1;
  private db.fennec.api.proto.FStatus status_;
  /**
   * <code>.db.fennec.api.proto.FStatus status = 1;</code>
   */
  public boolean hasStatus() {
    return status_ != null;
  }
  /**
   * <code>.db.fennec.api.proto.FStatus status = 1;</code>
   */
  public db.fennec.api.proto.FStatus getStatus() {
    return status_ == null ? db.fennec.api.proto.FStatus.getDefaultInstance() : status_;
  }
  /**
   * <code>.db.fennec.api.proto.FStatus status = 1;</code>
   */
  public db.fennec.api.proto.FStatusOrBuilder getStatusOrBuilder() {
    return getStatus();
  }

  public static final int RESULT_FIELD_NUMBER = 2;
  private db.fennec.proto.FResultProto result_;
  /**
   * <code>.db.fennec.proto.FResultProto result = 2;</code>
   */
  public boolean hasResult() {
    return result_ != null;
  }
  /**
   * <code>.db.fennec.proto.FResultProto result = 2;</code>
   */
  public db.fennec.proto.FResultProto getResult() {
    return result_ == null ? db.fennec.proto.FResultProto.getDefaultInstance() : result_;
  }
  /**
   * <code>.db.fennec.proto.FResultProto result = 2;</code>
   */
  public db.fennec.proto.FResultProtoOrBuilder getResultOrBuilder() {
    return getResult();
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (status_ != null) {
      output.writeMessage(1, getStatus());
    }
    if (result_ != null) {
      output.writeMessage(2, getResult());
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (status_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, getStatus());
    }
    if (result_ != null) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(2, getResult());
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof db.fennec.api.proto.FQueryResp)) {
      return super.equals(obj);
    }
    db.fennec.api.proto.FQueryResp other = (db.fennec.api.proto.FQueryResp) obj;

    boolean result = true;
    result = result && (hasStatus() == other.hasStatus());
    if (hasStatus()) {
      result = result && getStatus()
          .equals(other.getStatus());
    }
    result = result && (hasResult() == other.hasResult());
    if (hasResult()) {
      result = result && getResult()
          .equals(other.getResult());
    }
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (hasStatus()) {
      hash = (37 * hash) + STATUS_FIELD_NUMBER;
      hash = (53 * hash) + getStatus().hashCode();
    }
    if (hasResult()) {
      hash = (37 * hash) + RESULT_FIELD_NUMBER;
      hash = (53 * hash) + getResult().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static db.fennec.api.proto.FQueryResp parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static db.fennec.api.proto.FQueryResp parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static db.fennec.api.proto.FQueryResp parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static db.fennec.api.proto.FQueryResp parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static db.fennec.api.proto.FQueryResp parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static db.fennec.api.proto.FQueryResp parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static db.fennec.api.proto.FQueryResp parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static db.fennec.api.proto.FQueryResp parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static db.fennec.api.proto.FQueryResp parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static db.fennec.api.proto.FQueryResp parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static db.fennec.api.proto.FQueryResp parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static db.fennec.api.proto.FQueryResp parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(db.fennec.api.proto.FQueryResp prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * Protobuf type {@code db.fennec.api.proto.FQueryResp}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:db.fennec.api.proto.FQueryResp)
      db.fennec.api.proto.FQueryRespOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return db.fennec.api.proto.FennecServiceProto.internal_static_db_fennec_api_proto_FQueryResp_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return db.fennec.api.proto.FennecServiceProto.internal_static_db_fennec_api_proto_FQueryResp_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              db.fennec.api.proto.FQueryResp.class, db.fennec.api.proto.FQueryResp.Builder.class);
    }

    // Construct using db.fennec.api.proto.FQueryResp.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      if (statusBuilder_ == null) {
        status_ = null;
      } else {
        status_ = null;
        statusBuilder_ = null;
      }
      if (resultBuilder_ == null) {
        result_ = null;
      } else {
        result_ = null;
        resultBuilder_ = null;
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return db.fennec.api.proto.FennecServiceProto.internal_static_db_fennec_api_proto_FQueryResp_descriptor;
    }

    public db.fennec.api.proto.FQueryResp getDefaultInstanceForType() {
      return db.fennec.api.proto.FQueryResp.getDefaultInstance();
    }

    public db.fennec.api.proto.FQueryResp build() {
      db.fennec.api.proto.FQueryResp result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public db.fennec.api.proto.FQueryResp buildPartial() {
      db.fennec.api.proto.FQueryResp result = new db.fennec.api.proto.FQueryResp(this);
      if (statusBuilder_ == null) {
        result.status_ = status_;
      } else {
        result.status_ = statusBuilder_.build();
      }
      if (resultBuilder_ == null) {
        result.result_ = result_;
      } else {
        result.result_ = resultBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof db.fennec.api.proto.FQueryResp) {
        return mergeFrom((db.fennec.api.proto.FQueryResp)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(db.fennec.api.proto.FQueryResp other) {
      if (other == db.fennec.api.proto.FQueryResp.getDefaultInstance()) return this;
      if (other.hasStatus()) {
        mergeStatus(other.getStatus());
      }
      if (other.hasResult()) {
        mergeResult(other.getResult());
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      db.fennec.api.proto.FQueryResp parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (db.fennec.api.proto.FQueryResp) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private db.fennec.api.proto.FStatus status_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        db.fennec.api.proto.FStatus, db.fennec.api.proto.FStatus.Builder, db.fennec.api.proto.FStatusOrBuilder> statusBuilder_;
    /**
     * <code>.db.fennec.api.proto.FStatus status = 1;</code>
     */
    public boolean hasStatus() {
      return statusBuilder_ != null || status_ != null;
    }
    /**
     * <code>.db.fennec.api.proto.FStatus status = 1;</code>
     */
    public db.fennec.api.proto.FStatus getStatus() {
      if (statusBuilder_ == null) {
        return status_ == null ? db.fennec.api.proto.FStatus.getDefaultInstance() : status_;
      } else {
        return statusBuilder_.getMessage();
      }
    }
    /**
     * <code>.db.fennec.api.proto.FStatus status = 1;</code>
     */
    public Builder setStatus(db.fennec.api.proto.FStatus value) {
      if (statusBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        status_ = value;
        onChanged();
      } else {
        statusBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.db.fennec.api.proto.FStatus status = 1;</code>
     */
    public Builder setStatus(
        db.fennec.api.proto.FStatus.Builder builderForValue) {
      if (statusBuilder_ == null) {
        status_ = builderForValue.build();
        onChanged();
      } else {
        statusBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.db.fennec.api.proto.FStatus status = 1;</code>
     */
    public Builder mergeStatus(db.fennec.api.proto.FStatus value) {
      if (statusBuilder_ == null) {
        if (status_ != null) {
          status_ =
            db.fennec.api.proto.FStatus.newBuilder(status_).mergeFrom(value).buildPartial();
        } else {
          status_ = value;
        }
        onChanged();
      } else {
        statusBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.db.fennec.api.proto.FStatus status = 1;</code>
     */
    public Builder clearStatus() {
      if (statusBuilder_ == null) {
        status_ = null;
        onChanged();
      } else {
        status_ = null;
        statusBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.db.fennec.api.proto.FStatus status = 1;</code>
     */
    public db.fennec.api.proto.FStatus.Builder getStatusBuilder() {
      
      onChanged();
      return getStatusFieldBuilder().getBuilder();
    }
    /**
     * <code>.db.fennec.api.proto.FStatus status = 1;</code>
     */
    public db.fennec.api.proto.FStatusOrBuilder getStatusOrBuilder() {
      if (statusBuilder_ != null) {
        return statusBuilder_.getMessageOrBuilder();
      } else {
        return status_ == null ?
            db.fennec.api.proto.FStatus.getDefaultInstance() : status_;
      }
    }
    /**
     * <code>.db.fennec.api.proto.FStatus status = 1;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        db.fennec.api.proto.FStatus, db.fennec.api.proto.FStatus.Builder, db.fennec.api.proto.FStatusOrBuilder> 
        getStatusFieldBuilder() {
      if (statusBuilder_ == null) {
        statusBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            db.fennec.api.proto.FStatus, db.fennec.api.proto.FStatus.Builder, db.fennec.api.proto.FStatusOrBuilder>(
                getStatus(),
                getParentForChildren(),
                isClean());
        status_ = null;
      }
      return statusBuilder_;
    }

    private db.fennec.proto.FResultProto result_ = null;
    private com.google.protobuf.SingleFieldBuilderV3<
        db.fennec.proto.FResultProto, db.fennec.proto.FResultProto.Builder, db.fennec.proto.FResultProtoOrBuilder> resultBuilder_;
    /**
     * <code>.db.fennec.proto.FResultProto result = 2;</code>
     */
    public boolean hasResult() {
      return resultBuilder_ != null || result_ != null;
    }
    /**
     * <code>.db.fennec.proto.FResultProto result = 2;</code>
     */
    public db.fennec.proto.FResultProto getResult() {
      if (resultBuilder_ == null) {
        return result_ == null ? db.fennec.proto.FResultProto.getDefaultInstance() : result_;
      } else {
        return resultBuilder_.getMessage();
      }
    }
    /**
     * <code>.db.fennec.proto.FResultProto result = 2;</code>
     */
    public Builder setResult(db.fennec.proto.FResultProto value) {
      if (resultBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        result_ = value;
        onChanged();
      } else {
        resultBuilder_.setMessage(value);
      }

      return this;
    }
    /**
     * <code>.db.fennec.proto.FResultProto result = 2;</code>
     */
    public Builder setResult(
        db.fennec.proto.FResultProto.Builder builderForValue) {
      if (resultBuilder_ == null) {
        result_ = builderForValue.build();
        onChanged();
      } else {
        resultBuilder_.setMessage(builderForValue.build());
      }

      return this;
    }
    /**
     * <code>.db.fennec.proto.FResultProto result = 2;</code>
     */
    public Builder mergeResult(db.fennec.proto.FResultProto value) {
      if (resultBuilder_ == null) {
        if (result_ != null) {
          result_ =
            db.fennec.proto.FResultProto.newBuilder(result_).mergeFrom(value).buildPartial();
        } else {
          result_ = value;
        }
        onChanged();
      } else {
        resultBuilder_.mergeFrom(value);
      }

      return this;
    }
    /**
     * <code>.db.fennec.proto.FResultProto result = 2;</code>
     */
    public Builder clearResult() {
      if (resultBuilder_ == null) {
        result_ = null;
        onChanged();
      } else {
        result_ = null;
        resultBuilder_ = null;
      }

      return this;
    }
    /**
     * <code>.db.fennec.proto.FResultProto result = 2;</code>
     */
    public db.fennec.proto.FResultProto.Builder getResultBuilder() {
      
      onChanged();
      return getResultFieldBuilder().getBuilder();
    }
    /**
     * <code>.db.fennec.proto.FResultProto result = 2;</code>
     */
    public db.fennec.proto.FResultProtoOrBuilder getResultOrBuilder() {
      if (resultBuilder_ != null) {
        return resultBuilder_.getMessageOrBuilder();
      } else {
        return result_ == null ?
            db.fennec.proto.FResultProto.getDefaultInstance() : result_;
      }
    }
    /**
     * <code>.db.fennec.proto.FResultProto result = 2;</code>
     */
    private com.google.protobuf.SingleFieldBuilderV3<
        db.fennec.proto.FResultProto, db.fennec.proto.FResultProto.Builder, db.fennec.proto.FResultProtoOrBuilder> 
        getResultFieldBuilder() {
      if (resultBuilder_ == null) {
        resultBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
            db.fennec.proto.FResultProto, db.fennec.proto.FResultProto.Builder, db.fennec.proto.FResultProtoOrBuilder>(
                getResult(),
                getParentForChildren(),
                isClean());
        result_ = null;
      }
      return resultBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:db.fennec.api.proto.FQueryResp)
  }

  // @@protoc_insertion_point(class_scope:db.fennec.api.proto.FQueryResp)
  private static final db.fennec.api.proto.FQueryResp DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new db.fennec.api.proto.FQueryResp();
  }

  public static db.fennec.api.proto.FQueryResp getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FQueryResp>
      PARSER = new com.google.protobuf.AbstractParser<FQueryResp>() {
    public FQueryResp parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FQueryResp(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FQueryResp> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FQueryResp> getParserForType() {
    return PARSER;
  }

  public db.fennec.api.proto.FQueryResp getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

