// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FennecService.proto

package db.fennec.api.proto;

public interface FQueryRespOrBuilder extends
    // @@protoc_insertion_point(interface_extends:db.fennec.api.proto.FQueryResp)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>.db.fennec.api.proto.FStatus status = 1;</code>
   */
  boolean hasStatus();
  /**
   * <code>.db.fennec.api.proto.FStatus status = 1;</code>
   */
  db.fennec.api.proto.FStatus getStatus();
  /**
   * <code>.db.fennec.api.proto.FStatus status = 1;</code>
   */
  db.fennec.api.proto.FStatusOrBuilder getStatusOrBuilder();

  /**
   * <code>.db.fennec.proto.FResultProto result = 2;</code>
   */
  boolean hasResult();
  /**
   * <code>.db.fennec.proto.FResultProto result = 2;</code>
   */
  db.fennec.proto.FResultProto getResult();
  /**
   * <code>.db.fennec.proto.FResultProto result = 2;</code>
   */
  db.fennec.proto.FResultProtoOrBuilder getResultOrBuilder();
}
