// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FennecService.proto

package db.fennec.api.proto;

public interface FRemoveReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:db.fennec.api.proto.FRemoveReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>int64 in_range_low = 1;</code>
   */
  long getInRangeLow();

  /**
   * <code>int64 in_range_high = 2;</code>
   */
  long getInRangeHigh();

  /**
   * <code>string field = 3;</code>
   */
  java.lang.String getField();
  /**
   * <code>string field = 3;</code>
   */
  com.google.protobuf.ByteString
      getFieldBytes();

  /**
   * <code>string namespace = 4;</code>
   */
  java.lang.String getNamespace();
  /**
   * <code>string namespace = 4;</code>
   */
  com.google.protobuf.ByteString
      getNamespaceBytes();
}
