// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FennecService.proto

package db.fennec.api.proto;

public interface FRemoveNSReqOrBuilder extends
    // @@protoc_insertion_point(interface_extends:db.fennec.api.proto.FRemoveNSReq)
    com.google.protobuf.MessageOrBuilder {

  /**
   * <code>string namespace = 1;</code>
   */
  java.lang.String getNamespace();
  /**
   * <code>string namespace = 1;</code>
   */
  com.google.protobuf.ByteString
      getNamespaceBytes();
}
