// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FennecService.proto

package db.fennec.api.proto;

/**
 * <pre>
 * remove FIELD (in range)
 * </pre>
 *
 * Protobuf type {@code db.fennec.api.proto.FRemoveReq}
 */
public  final class FRemoveReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:db.fennec.api.proto.FRemoveReq)
    FRemoveReqOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FRemoveReq.newBuilder() to construct.
  private FRemoveReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FRemoveReq() {
    inRangeLow_ = 0L;
    inRangeHigh_ = 0L;
    field_ = "";
    namespace_ = "";
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FRemoveReq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 8: {

            inRangeLow_ = input.readInt64();
            break;
          }
          case 16: {

            inRangeHigh_ = input.readInt64();
            break;
          }
          case 26: {
            java.lang.String s = input.readStringRequireUtf8();

            field_ = s;
            break;
          }
          case 34: {
            java.lang.String s = input.readStringRequireUtf8();

            namespace_ = s;
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return db.fennec.api.proto.FennecServiceProto.internal_static_db_fennec_api_proto_FRemoveReq_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return db.fennec.api.proto.FennecServiceProto.internal_static_db_fennec_api_proto_FRemoveReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            db.fennec.api.proto.FRemoveReq.class, db.fennec.api.proto.FRemoveReq.Builder.class);
  }

  public static final int IN_RANGE_LOW_FIELD_NUMBER = 1;
  private long inRangeLow_;
  /**
   * <code>int64 in_range_low = 1;</code>
   */
  public long getInRangeLow() {
    return inRangeLow_;
  }

  public static final int IN_RANGE_HIGH_FIELD_NUMBER = 2;
  private long inRangeHigh_;
  /**
   * <code>int64 in_range_high = 2;</code>
   */
  public long getInRangeHigh() {
    return inRangeHigh_;
  }

  public static final int FIELD_FIELD_NUMBER = 3;
  private volatile java.lang.Object field_;
  /**
   * <code>string field = 3;</code>
   */
  public java.lang.String getField() {
    java.lang.Object ref = field_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      field_ = s;
      return s;
    }
  }
  /**
   * <code>string field = 3;</code>
   */
  public com.google.protobuf.ByteString
      getFieldBytes() {
    java.lang.Object ref = field_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      field_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  public static final int NAMESPACE_FIELD_NUMBER = 4;
  private volatile java.lang.Object namespace_;
  /**
   * <code>string namespace = 4;</code>
   */
  public java.lang.String getNamespace() {
    java.lang.Object ref = namespace_;
    if (ref instanceof java.lang.String) {
      return (java.lang.String) ref;
    } else {
      com.google.protobuf.ByteString bs = 
          (com.google.protobuf.ByteString) ref;
      java.lang.String s = bs.toStringUtf8();
      namespace_ = s;
      return s;
    }
  }
  /**
   * <code>string namespace = 4;</code>
   */
  public com.google.protobuf.ByteString
      getNamespaceBytes() {
    java.lang.Object ref = namespace_;
    if (ref instanceof java.lang.String) {
      com.google.protobuf.ByteString b = 
          com.google.protobuf.ByteString.copyFromUtf8(
              (java.lang.String) ref);
      namespace_ = b;
      return b;
    } else {
      return (com.google.protobuf.ByteString) ref;
    }
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (inRangeLow_ != 0L) {
      output.writeInt64(1, inRangeLow_);
    }
    if (inRangeHigh_ != 0L) {
      output.writeInt64(2, inRangeHigh_);
    }
    if (!getFieldBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 3, field_);
    }
    if (!getNamespaceBytes().isEmpty()) {
      com.google.protobuf.GeneratedMessageV3.writeString(output, 4, namespace_);
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    if (inRangeLow_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(1, inRangeLow_);
    }
    if (inRangeHigh_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, inRangeHigh_);
    }
    if (!getFieldBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, field_);
    }
    if (!getNamespaceBytes().isEmpty()) {
      size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, namespace_);
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof db.fennec.api.proto.FRemoveReq)) {
      return super.equals(obj);
    }
    db.fennec.api.proto.FRemoveReq other = (db.fennec.api.proto.FRemoveReq) obj;

    boolean result = true;
    result = result && (getInRangeLow()
        == other.getInRangeLow());
    result = result && (getInRangeHigh()
        == other.getInRangeHigh());
    result = result && getField()
        .equals(other.getField());
    result = result && getNamespace()
        .equals(other.getNamespace());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    hash = (37 * hash) + IN_RANGE_LOW_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getInRangeLow());
    hash = (37 * hash) + IN_RANGE_HIGH_FIELD_NUMBER;
    hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
        getInRangeHigh());
    hash = (37 * hash) + FIELD_FIELD_NUMBER;
    hash = (53 * hash) + getField().hashCode();
    hash = (37 * hash) + NAMESPACE_FIELD_NUMBER;
    hash = (53 * hash) + getNamespace().hashCode();
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static db.fennec.api.proto.FRemoveReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static db.fennec.api.proto.FRemoveReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static db.fennec.api.proto.FRemoveReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static db.fennec.api.proto.FRemoveReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static db.fennec.api.proto.FRemoveReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static db.fennec.api.proto.FRemoveReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static db.fennec.api.proto.FRemoveReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static db.fennec.api.proto.FRemoveReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static db.fennec.api.proto.FRemoveReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static db.fennec.api.proto.FRemoveReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static db.fennec.api.proto.FRemoveReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static db.fennec.api.proto.FRemoveReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(db.fennec.api.proto.FRemoveReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * remove FIELD (in range)
   * </pre>
   *
   * Protobuf type {@code db.fennec.api.proto.FRemoveReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:db.fennec.api.proto.FRemoveReq)
      db.fennec.api.proto.FRemoveReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return db.fennec.api.proto.FennecServiceProto.internal_static_db_fennec_api_proto_FRemoveReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return db.fennec.api.proto.FennecServiceProto.internal_static_db_fennec_api_proto_FRemoveReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              db.fennec.api.proto.FRemoveReq.class, db.fennec.api.proto.FRemoveReq.Builder.class);
    }

    // Construct using db.fennec.api.proto.FRemoveReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
      }
    }
    public Builder clear() {
      super.clear();
      inRangeLow_ = 0L;

      inRangeHigh_ = 0L;

      field_ = "";

      namespace_ = "";

      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return db.fennec.api.proto.FennecServiceProto.internal_static_db_fennec_api_proto_FRemoveReq_descriptor;
    }

    public db.fennec.api.proto.FRemoveReq getDefaultInstanceForType() {
      return db.fennec.api.proto.FRemoveReq.getDefaultInstance();
    }

    public db.fennec.api.proto.FRemoveReq build() {
      db.fennec.api.proto.FRemoveReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public db.fennec.api.proto.FRemoveReq buildPartial() {
      db.fennec.api.proto.FRemoveReq result = new db.fennec.api.proto.FRemoveReq(this);
      result.inRangeLow_ = inRangeLow_;
      result.inRangeHigh_ = inRangeHigh_;
      result.field_ = field_;
      result.namespace_ = namespace_;
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof db.fennec.api.proto.FRemoveReq) {
        return mergeFrom((db.fennec.api.proto.FRemoveReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(db.fennec.api.proto.FRemoveReq other) {
      if (other == db.fennec.api.proto.FRemoveReq.getDefaultInstance()) return this;
      if (other.getInRangeLow() != 0L) {
        setInRangeLow(other.getInRangeLow());
      }
      if (other.getInRangeHigh() != 0L) {
        setInRangeHigh(other.getInRangeHigh());
      }
      if (!other.getField().isEmpty()) {
        field_ = other.field_;
        onChanged();
      }
      if (!other.getNamespace().isEmpty()) {
        namespace_ = other.namespace_;
        onChanged();
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      db.fennec.api.proto.FRemoveReq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (db.fennec.api.proto.FRemoveReq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }

    private long inRangeLow_ ;
    /**
     * <code>int64 in_range_low = 1;</code>
     */
    public long getInRangeLow() {
      return inRangeLow_;
    }
    /**
     * <code>int64 in_range_low = 1;</code>
     */
    public Builder setInRangeLow(long value) {
      
      inRangeLow_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 in_range_low = 1;</code>
     */
    public Builder clearInRangeLow() {
      
      inRangeLow_ = 0L;
      onChanged();
      return this;
    }

    private long inRangeHigh_ ;
    /**
     * <code>int64 in_range_high = 2;</code>
     */
    public long getInRangeHigh() {
      return inRangeHigh_;
    }
    /**
     * <code>int64 in_range_high = 2;</code>
     */
    public Builder setInRangeHigh(long value) {
      
      inRangeHigh_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>int64 in_range_high = 2;</code>
     */
    public Builder clearInRangeHigh() {
      
      inRangeHigh_ = 0L;
      onChanged();
      return this;
    }

    private java.lang.Object field_ = "";
    /**
     * <code>string field = 3;</code>
     */
    public java.lang.String getField() {
      java.lang.Object ref = field_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        field_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string field = 3;</code>
     */
    public com.google.protobuf.ByteString
        getFieldBytes() {
      java.lang.Object ref = field_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        field_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string field = 3;</code>
     */
    public Builder setField(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      field_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string field = 3;</code>
     */
    public Builder clearField() {
      
      field_ = getDefaultInstance().getField();
      onChanged();
      return this;
    }
    /**
     * <code>string field = 3;</code>
     */
    public Builder setFieldBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      field_ = value;
      onChanged();
      return this;
    }

    private java.lang.Object namespace_ = "";
    /**
     * <code>string namespace = 4;</code>
     */
    public java.lang.String getNamespace() {
      java.lang.Object ref = namespace_;
      if (!(ref instanceof java.lang.String)) {
        com.google.protobuf.ByteString bs =
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        namespace_ = s;
        return s;
      } else {
        return (java.lang.String) ref;
      }
    }
    /**
     * <code>string namespace = 4;</code>
     */
    public com.google.protobuf.ByteString
        getNamespaceBytes() {
      java.lang.Object ref = namespace_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        namespace_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    /**
     * <code>string namespace = 4;</code>
     */
    public Builder setNamespace(
        java.lang.String value) {
      if (value == null) {
    throw new NullPointerException();
  }
  
      namespace_ = value;
      onChanged();
      return this;
    }
    /**
     * <code>string namespace = 4;</code>
     */
    public Builder clearNamespace() {
      
      namespace_ = getDefaultInstance().getNamespace();
      onChanged();
      return this;
    }
    /**
     * <code>string namespace = 4;</code>
     */
    public Builder setNamespaceBytes(
        com.google.protobuf.ByteString value) {
      if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
      
      namespace_ = value;
      onChanged();
      return this;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:db.fennec.api.proto.FRemoveReq)
  }

  // @@protoc_insertion_point(class_scope:db.fennec.api.proto.FRemoveReq)
  private static final db.fennec.api.proto.FRemoveReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new db.fennec.api.proto.FRemoveReq();
  }

  public static db.fennec.api.proto.FRemoveReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FRemoveReq>
      PARSER = new com.google.protobuf.AbstractParser<FRemoveReq>() {
    public FRemoveReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FRemoveReq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FRemoveReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FRemoveReq> getParserForType() {
    return PARSER;
  }

  public db.fennec.api.proto.FRemoveReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

