// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: FennecService.proto

package db.fennec.api.proto;

/**
 * <pre>
 * INSERT / UPSERT
 * </pre>
 *
 * Protobuf type {@code db.fennec.api.proto.FWriteReq}
 */
public  final class FWriteReq extends
    com.google.protobuf.GeneratedMessageV3 implements
    // @@protoc_insertion_point(message_implements:db.fennec.api.proto.FWriteReq)
    FWriteReqOrBuilder {
private static final long serialVersionUID = 0L;
  // Use FWriteReq.newBuilder() to construct.
  private FWriteReq(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
    super(builder);
  }
  private FWriteReq() {
    payload_ = java.util.Collections.emptyList();
  }

  @java.lang.Override
  public final com.google.protobuf.UnknownFieldSet
  getUnknownFields() {
    return this.unknownFields;
  }
  private FWriteReq(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    this();
    if (extensionRegistry == null) {
      throw new java.lang.NullPointerException();
    }
    int mutable_bitField0_ = 0;
    com.google.protobuf.UnknownFieldSet.Builder unknownFields =
        com.google.protobuf.UnknownFieldSet.newBuilder();
    try {
      boolean done = false;
      while (!done) {
        int tag = input.readTag();
        switch (tag) {
          case 0:
            done = true;
            break;
          default: {
            if (!parseUnknownFieldProto3(
                input, unknownFields, extensionRegistry, tag)) {
              done = true;
            }
            break;
          }
          case 10: {
            if (!((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
              payload_ = new java.util.ArrayList<db.fennec.proto.FDataEntryProto>();
              mutable_bitField0_ |= 0x00000001;
            }
            payload_.add(
                input.readMessage(db.fennec.proto.FDataEntryProto.parser(), extensionRegistry));
            break;
          }
        }
      }
    } catch (com.google.protobuf.InvalidProtocolBufferException e) {
      throw e.setUnfinishedMessage(this);
    } catch (java.io.IOException e) {
      throw new com.google.protobuf.InvalidProtocolBufferException(
          e).setUnfinishedMessage(this);
    } finally {
      if (((mutable_bitField0_ & 0x00000001) == 0x00000001)) {
        payload_ = java.util.Collections.unmodifiableList(payload_);
      }
      this.unknownFields = unknownFields.build();
      makeExtensionsImmutable();
    }
  }
  public static final com.google.protobuf.Descriptors.Descriptor
      getDescriptor() {
    return db.fennec.api.proto.FennecServiceProto.internal_static_db_fennec_api_proto_FWriteReq_descriptor;
  }

  protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internalGetFieldAccessorTable() {
    return db.fennec.api.proto.FennecServiceProto.internal_static_db_fennec_api_proto_FWriteReq_fieldAccessorTable
        .ensureFieldAccessorsInitialized(
            db.fennec.api.proto.FWriteReq.class, db.fennec.api.proto.FWriteReq.Builder.class);
  }

  public static final int PAYLOAD_FIELD_NUMBER = 1;
  private java.util.List<db.fennec.proto.FDataEntryProto> payload_;
  /**
   * <code>repeated .db.fennec.proto.FDataEntryProto payload = 1;</code>
   */
  public java.util.List<db.fennec.proto.FDataEntryProto> getPayloadList() {
    return payload_;
  }
  /**
   * <code>repeated .db.fennec.proto.FDataEntryProto payload = 1;</code>
   */
  public java.util.List<? extends db.fennec.proto.FDataEntryProtoOrBuilder> 
      getPayloadOrBuilderList() {
    return payload_;
  }
  /**
   * <code>repeated .db.fennec.proto.FDataEntryProto payload = 1;</code>
   */
  public int getPayloadCount() {
    return payload_.size();
  }
  /**
   * <code>repeated .db.fennec.proto.FDataEntryProto payload = 1;</code>
   */
  public db.fennec.proto.FDataEntryProto getPayload(int index) {
    return payload_.get(index);
  }
  /**
   * <code>repeated .db.fennec.proto.FDataEntryProto payload = 1;</code>
   */
  public db.fennec.proto.FDataEntryProtoOrBuilder getPayloadOrBuilder(
      int index) {
    return payload_.get(index);
  }

  private byte memoizedIsInitialized = -1;
  public final boolean isInitialized() {
    byte isInitialized = memoizedIsInitialized;
    if (isInitialized == 1) return true;
    if (isInitialized == 0) return false;

    memoizedIsInitialized = 1;
    return true;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    for (int i = 0; i < payload_.size(); i++) {
      output.writeMessage(1, payload_.get(i));
    }
    unknownFields.writeTo(output);
  }

  public int getSerializedSize() {
    int size = memoizedSize;
    if (size != -1) return size;

    size = 0;
    for (int i = 0; i < payload_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(1, payload_.get(i));
    }
    size += unknownFields.getSerializedSize();
    memoizedSize = size;
    return size;
  }

  @java.lang.Override
  public boolean equals(final java.lang.Object obj) {
    if (obj == this) {
     return true;
    }
    if (!(obj instanceof db.fennec.api.proto.FWriteReq)) {
      return super.equals(obj);
    }
    db.fennec.api.proto.FWriteReq other = (db.fennec.api.proto.FWriteReq) obj;

    boolean result = true;
    result = result && getPayloadList()
        .equals(other.getPayloadList());
    result = result && unknownFields.equals(other.unknownFields);
    return result;
  }

  @java.lang.Override
  public int hashCode() {
    if (memoizedHashCode != 0) {
      return memoizedHashCode;
    }
    int hash = 41;
    hash = (19 * hash) + getDescriptor().hashCode();
    if (getPayloadCount() > 0) {
      hash = (37 * hash) + PAYLOAD_FIELD_NUMBER;
      hash = (53 * hash) + getPayloadList().hashCode();
    }
    hash = (29 * hash) + unknownFields.hashCode();
    memoizedHashCode = hash;
    return hash;
  }

  public static db.fennec.api.proto.FWriteReq parseFrom(
      java.nio.ByteBuffer data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static db.fennec.api.proto.FWriteReq parseFrom(
      java.nio.ByteBuffer data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static db.fennec.api.proto.FWriteReq parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static db.fennec.api.proto.FWriteReq parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static db.fennec.api.proto.FWriteReq parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data);
  }
  public static db.fennec.api.proto.FWriteReq parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return PARSER.parseFrom(data, extensionRegistry);
  }
  public static db.fennec.api.proto.FWriteReq parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static db.fennec.api.proto.FWriteReq parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }
  public static db.fennec.api.proto.FWriteReq parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input);
  }
  public static db.fennec.api.proto.FWriteReq parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
  }
  public static db.fennec.api.proto.FWriteReq parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input);
  }
  public static db.fennec.api.proto.FWriteReq parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageV3
        .parseWithIOException(PARSER, input, extensionRegistry);
  }

  public Builder newBuilderForType() { return newBuilder(); }
  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(db.fennec.api.proto.FWriteReq prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }
  public Builder toBuilder() {
    return this == DEFAULT_INSTANCE
        ? new Builder() : new Builder().mergeFrom(this);
  }

  @java.lang.Override
  protected Builder newBuilderForType(
      com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
    Builder builder = new Builder(parent);
    return builder;
  }
  /**
   * <pre>
   * INSERT / UPSERT
   * </pre>
   *
   * Protobuf type {@code db.fennec.api.proto.FWriteReq}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
      // @@protoc_insertion_point(builder_implements:db.fennec.api.proto.FWriteReq)
      db.fennec.api.proto.FWriteReqOrBuilder {
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return db.fennec.api.proto.FennecServiceProto.internal_static_db_fennec_api_proto_FWriteReq_descriptor;
    }

    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return db.fennec.api.proto.FennecServiceProto.internal_static_db_fennec_api_proto_FWriteReq_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              db.fennec.api.proto.FWriteReq.class, db.fennec.api.proto.FWriteReq.Builder.class);
    }

    // Construct using db.fennec.api.proto.FWriteReq.newBuilder()
    private Builder() {
      maybeForceBuilderInitialization();
    }

    private Builder(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      super(parent);
      maybeForceBuilderInitialization();
    }
    private void maybeForceBuilderInitialization() {
      if (com.google.protobuf.GeneratedMessageV3
              .alwaysUseFieldBuilders) {
        getPayloadFieldBuilder();
      }
    }
    public Builder clear() {
      super.clear();
      if (payloadBuilder_ == null) {
        payload_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
      } else {
        payloadBuilder_.clear();
      }
      return this;
    }

    public com.google.protobuf.Descriptors.Descriptor
        getDescriptorForType() {
      return db.fennec.api.proto.FennecServiceProto.internal_static_db_fennec_api_proto_FWriteReq_descriptor;
    }

    public db.fennec.api.proto.FWriteReq getDefaultInstanceForType() {
      return db.fennec.api.proto.FWriteReq.getDefaultInstance();
    }

    public db.fennec.api.proto.FWriteReq build() {
      db.fennec.api.proto.FWriteReq result = buildPartial();
      if (!result.isInitialized()) {
        throw newUninitializedMessageException(result);
      }
      return result;
    }

    public db.fennec.api.proto.FWriteReq buildPartial() {
      db.fennec.api.proto.FWriteReq result = new db.fennec.api.proto.FWriteReq(this);
      int from_bitField0_ = bitField0_;
      if (payloadBuilder_ == null) {
        if (((bitField0_ & 0x00000001) == 0x00000001)) {
          payload_ = java.util.Collections.unmodifiableList(payload_);
          bitField0_ = (bitField0_ & ~0x00000001);
        }
        result.payload_ = payload_;
      } else {
        result.payload_ = payloadBuilder_.build();
      }
      onBuilt();
      return result;
    }

    public Builder clone() {
      return (Builder) super.clone();
    }
    public Builder setField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.setField(field, value);
    }
    public Builder clearField(
        com.google.protobuf.Descriptors.FieldDescriptor field) {
      return (Builder) super.clearField(field);
    }
    public Builder clearOneof(
        com.google.protobuf.Descriptors.OneofDescriptor oneof) {
      return (Builder) super.clearOneof(oneof);
    }
    public Builder setRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        int index, java.lang.Object value) {
      return (Builder) super.setRepeatedField(field, index, value);
    }
    public Builder addRepeatedField(
        com.google.protobuf.Descriptors.FieldDescriptor field,
        java.lang.Object value) {
      return (Builder) super.addRepeatedField(field, value);
    }
    public Builder mergeFrom(com.google.protobuf.Message other) {
      if (other instanceof db.fennec.api.proto.FWriteReq) {
        return mergeFrom((db.fennec.api.proto.FWriteReq)other);
      } else {
        super.mergeFrom(other);
        return this;
      }
    }

    public Builder mergeFrom(db.fennec.api.proto.FWriteReq other) {
      if (other == db.fennec.api.proto.FWriteReq.getDefaultInstance()) return this;
      if (payloadBuilder_ == null) {
        if (!other.payload_.isEmpty()) {
          if (payload_.isEmpty()) {
            payload_ = other.payload_;
            bitField0_ = (bitField0_ & ~0x00000001);
          } else {
            ensurePayloadIsMutable();
            payload_.addAll(other.payload_);
          }
          onChanged();
        }
      } else {
        if (!other.payload_.isEmpty()) {
          if (payloadBuilder_.isEmpty()) {
            payloadBuilder_.dispose();
            payloadBuilder_ = null;
            payload_ = other.payload_;
            bitField0_ = (bitField0_ & ~0x00000001);
            payloadBuilder_ = 
              com.google.protobuf.GeneratedMessageV3.alwaysUseFieldBuilders ?
                 getPayloadFieldBuilder() : null;
          } else {
            payloadBuilder_.addAllMessages(other.payload_);
          }
        }
      }
      this.mergeUnknownFields(other.unknownFields);
      onChanged();
      return this;
    }

    public final boolean isInitialized() {
      return true;
    }

    public Builder mergeFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      db.fennec.api.proto.FWriteReq parsedMessage = null;
      try {
        parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        parsedMessage = (db.fennec.api.proto.FWriteReq) e.getUnfinishedMessage();
        throw e.unwrapIOException();
      } finally {
        if (parsedMessage != null) {
          mergeFrom(parsedMessage);
        }
      }
      return this;
    }
    private int bitField0_;

    private java.util.List<db.fennec.proto.FDataEntryProto> payload_ =
      java.util.Collections.emptyList();
    private void ensurePayloadIsMutable() {
      if (!((bitField0_ & 0x00000001) == 0x00000001)) {
        payload_ = new java.util.ArrayList<db.fennec.proto.FDataEntryProto>(payload_);
        bitField0_ |= 0x00000001;
       }
    }

    private com.google.protobuf.RepeatedFieldBuilderV3<
        db.fennec.proto.FDataEntryProto, db.fennec.proto.FDataEntryProto.Builder, db.fennec.proto.FDataEntryProtoOrBuilder> payloadBuilder_;

    /**
     * <code>repeated .db.fennec.proto.FDataEntryProto payload = 1;</code>
     */
    public java.util.List<db.fennec.proto.FDataEntryProto> getPayloadList() {
      if (payloadBuilder_ == null) {
        return java.util.Collections.unmodifiableList(payload_);
      } else {
        return payloadBuilder_.getMessageList();
      }
    }
    /**
     * <code>repeated .db.fennec.proto.FDataEntryProto payload = 1;</code>
     */
    public int getPayloadCount() {
      if (payloadBuilder_ == null) {
        return payload_.size();
      } else {
        return payloadBuilder_.getCount();
      }
    }
    /**
     * <code>repeated .db.fennec.proto.FDataEntryProto payload = 1;</code>
     */
    public db.fennec.proto.FDataEntryProto getPayload(int index) {
      if (payloadBuilder_ == null) {
        return payload_.get(index);
      } else {
        return payloadBuilder_.getMessage(index);
      }
    }
    /**
     * <code>repeated .db.fennec.proto.FDataEntryProto payload = 1;</code>
     */
    public Builder setPayload(
        int index, db.fennec.proto.FDataEntryProto value) {
      if (payloadBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePayloadIsMutable();
        payload_.set(index, value);
        onChanged();
      } else {
        payloadBuilder_.setMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .db.fennec.proto.FDataEntryProto payload = 1;</code>
     */
    public Builder setPayload(
        int index, db.fennec.proto.FDataEntryProto.Builder builderForValue) {
      if (payloadBuilder_ == null) {
        ensurePayloadIsMutable();
        payload_.set(index, builderForValue.build());
        onChanged();
      } else {
        payloadBuilder_.setMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .db.fennec.proto.FDataEntryProto payload = 1;</code>
     */
    public Builder addPayload(db.fennec.proto.FDataEntryProto value) {
      if (payloadBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePayloadIsMutable();
        payload_.add(value);
        onChanged();
      } else {
        payloadBuilder_.addMessage(value);
      }
      return this;
    }
    /**
     * <code>repeated .db.fennec.proto.FDataEntryProto payload = 1;</code>
     */
    public Builder addPayload(
        int index, db.fennec.proto.FDataEntryProto value) {
      if (payloadBuilder_ == null) {
        if (value == null) {
          throw new NullPointerException();
        }
        ensurePayloadIsMutable();
        payload_.add(index, value);
        onChanged();
      } else {
        payloadBuilder_.addMessage(index, value);
      }
      return this;
    }
    /**
     * <code>repeated .db.fennec.proto.FDataEntryProto payload = 1;</code>
     */
    public Builder addPayload(
        db.fennec.proto.FDataEntryProto.Builder builderForValue) {
      if (payloadBuilder_ == null) {
        ensurePayloadIsMutable();
        payload_.add(builderForValue.build());
        onChanged();
      } else {
        payloadBuilder_.addMessage(builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .db.fennec.proto.FDataEntryProto payload = 1;</code>
     */
    public Builder addPayload(
        int index, db.fennec.proto.FDataEntryProto.Builder builderForValue) {
      if (payloadBuilder_ == null) {
        ensurePayloadIsMutable();
        payload_.add(index, builderForValue.build());
        onChanged();
      } else {
        payloadBuilder_.addMessage(index, builderForValue.build());
      }
      return this;
    }
    /**
     * <code>repeated .db.fennec.proto.FDataEntryProto payload = 1;</code>
     */
    public Builder addAllPayload(
        java.lang.Iterable<? extends db.fennec.proto.FDataEntryProto> values) {
      if (payloadBuilder_ == null) {
        ensurePayloadIsMutable();
        com.google.protobuf.AbstractMessageLite.Builder.addAll(
            values, payload_);
        onChanged();
      } else {
        payloadBuilder_.addAllMessages(values);
      }
      return this;
    }
    /**
     * <code>repeated .db.fennec.proto.FDataEntryProto payload = 1;</code>
     */
    public Builder clearPayload() {
      if (payloadBuilder_ == null) {
        payload_ = java.util.Collections.emptyList();
        bitField0_ = (bitField0_ & ~0x00000001);
        onChanged();
      } else {
        payloadBuilder_.clear();
      }
      return this;
    }
    /**
     * <code>repeated .db.fennec.proto.FDataEntryProto payload = 1;</code>
     */
    public Builder removePayload(int index) {
      if (payloadBuilder_ == null) {
        ensurePayloadIsMutable();
        payload_.remove(index);
        onChanged();
      } else {
        payloadBuilder_.remove(index);
      }
      return this;
    }
    /**
     * <code>repeated .db.fennec.proto.FDataEntryProto payload = 1;</code>
     */
    public db.fennec.proto.FDataEntryProto.Builder getPayloadBuilder(
        int index) {
      return getPayloadFieldBuilder().getBuilder(index);
    }
    /**
     * <code>repeated .db.fennec.proto.FDataEntryProto payload = 1;</code>
     */
    public db.fennec.proto.FDataEntryProtoOrBuilder getPayloadOrBuilder(
        int index) {
      if (payloadBuilder_ == null) {
        return payload_.get(index);  } else {
        return payloadBuilder_.getMessageOrBuilder(index);
      }
    }
    /**
     * <code>repeated .db.fennec.proto.FDataEntryProto payload = 1;</code>
     */
    public java.util.List<? extends db.fennec.proto.FDataEntryProtoOrBuilder> 
         getPayloadOrBuilderList() {
      if (payloadBuilder_ != null) {
        return payloadBuilder_.getMessageOrBuilderList();
      } else {
        return java.util.Collections.unmodifiableList(payload_);
      }
    }
    /**
     * <code>repeated .db.fennec.proto.FDataEntryProto payload = 1;</code>
     */
    public db.fennec.proto.FDataEntryProto.Builder addPayloadBuilder() {
      return getPayloadFieldBuilder().addBuilder(
          db.fennec.proto.FDataEntryProto.getDefaultInstance());
    }
    /**
     * <code>repeated .db.fennec.proto.FDataEntryProto payload = 1;</code>
     */
    public db.fennec.proto.FDataEntryProto.Builder addPayloadBuilder(
        int index) {
      return getPayloadFieldBuilder().addBuilder(
          index, db.fennec.proto.FDataEntryProto.getDefaultInstance());
    }
    /**
     * <code>repeated .db.fennec.proto.FDataEntryProto payload = 1;</code>
     */
    public java.util.List<db.fennec.proto.FDataEntryProto.Builder> 
         getPayloadBuilderList() {
      return getPayloadFieldBuilder().getBuilderList();
    }
    private com.google.protobuf.RepeatedFieldBuilderV3<
        db.fennec.proto.FDataEntryProto, db.fennec.proto.FDataEntryProto.Builder, db.fennec.proto.FDataEntryProtoOrBuilder> 
        getPayloadFieldBuilder() {
      if (payloadBuilder_ == null) {
        payloadBuilder_ = new com.google.protobuf.RepeatedFieldBuilderV3<
            db.fennec.proto.FDataEntryProto, db.fennec.proto.FDataEntryProto.Builder, db.fennec.proto.FDataEntryProtoOrBuilder>(
                payload_,
                ((bitField0_ & 0x00000001) == 0x00000001),
                getParentForChildren(),
                isClean());
        payload_ = null;
      }
      return payloadBuilder_;
    }
    public final Builder setUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.setUnknownFieldsProto3(unknownFields);
    }

    public final Builder mergeUnknownFields(
        final com.google.protobuf.UnknownFieldSet unknownFields) {
      return super.mergeUnknownFields(unknownFields);
    }


    // @@protoc_insertion_point(builder_scope:db.fennec.api.proto.FWriteReq)
  }

  // @@protoc_insertion_point(class_scope:db.fennec.api.proto.FWriteReq)
  private static final db.fennec.api.proto.FWriteReq DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new db.fennec.api.proto.FWriteReq();
  }

  public static db.fennec.api.proto.FWriteReq getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static final com.google.protobuf.Parser<FWriteReq>
      PARSER = new com.google.protobuf.AbstractParser<FWriteReq>() {
    public FWriteReq parsePartialFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return new FWriteReq(input, extensionRegistry);
    }
  };

  public static com.google.protobuf.Parser<FWriteReq> parser() {
    return PARSER;
  }

  @java.lang.Override
  public com.google.protobuf.Parser<FWriteReq> getParserForType() {
    return PARSER;
  }

  public db.fennec.api.proto.FWriteReq getDefaultInstanceForType() {
    return DEFAULT_INSTANCE;
  }

}

